export interface Itinerary {
  id: number;
  userName: string;
  userAvatar: string;
  destination: string;
  duration: string;
  budget: string;
  likes: number;
  saves: number;
  thumbnail: string;
  description: string;
  tags?: string[];
}

// Category-specific itineraries
export const categoryItineraries: Record<string, Itinerary[]> = {
  'beach-paradise': [
    {
      id: 1,
      userName: "Emma Rodriguez",
      userAvatar: "https://i.pravatar.cc/150?img=5",
      destination: "Bali, Indonesia",
      duration: "10 days",
      budget: "$1,800",
      likes: 891,
      saves: 456,
      thumbnail: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
      description: "Beach paradise with yoga retreats, temple visits, and stunning sunsets.",
    },
    {
      id: 2,
      userName: "Olivia Martinez",
      userAvatar: "https://i.pravatar.cc/150?img=9",
      destination: "Santorini, Greece",
      duration: "6 days",
      budget: "$3,500",
      likes: 1024,
      saves: 567,
      thumbnail: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
      description: "Luxury escape in the Greek islands with breathtaking views and amazing food.",
    },
    {
      id: 3,
      userName: "Carlos Santos",
      userAvatar: "https://i.pravatar.cc/150?img=13",
      destination: "Maldives",
      duration: "8 days",
      budget: "$5,000",
      likes: 1256,
      saves: 689,
      thumbnail: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
      description: "Ultimate tropical paradise with overwater bungalows and crystal-clear waters.",
    },
  ],
  'cultural-heritage': [
    {
      id: 4,
      userName: "Sarah Johnson",
      userAvatar: "https://i.pravatar.cc/150?img=1",
      destination: "Tokyo, Japan",
      duration: "7 days",
      budget: "$2,500",
      likes: 342,
      saves: 128,
      thumbnail: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
      description: "Amazing week exploring Tokyo's vibrant neighborhoods, from Shibuya to Akihabara!",
    },
    {
      id: 5,
      userName: "Michael Chen",
      userAvatar: "https://i.pravatar.cc/150?img=12",
      destination: "Paris, France",
      duration: "5 days",
      budget: "$3,200",
      likes: 567,
      saves: 234,
      thumbnail: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
      description: "Romantic getaway through the City of Lights with amazing café stops.",
    },
    {
      id: 6,
      userName: "Lisa Wong",
      userAvatar: "https://i.pravatar.cc/150?img=16",
      destination: "Rome, Italy",
      duration: "6 days",
      budget: "$2,800",
      likes: 689,
      saves: 312,
      thumbnail: "https://images.unsplash.com/photo-1552832860-cfde67570dbb?w=800",
      description: "Journey through ancient history and Renaissance art in the Eternal City.",
    },
  ],
  'food-adventure': [
    {
      id: 7,
      userName: "David Kim",
      userAvatar: "https://i.pravatar.cc/150?img=8",
      destination: "Bangkok, Thailand",
      duration: "5 days",
      budget: "$1,500",
      likes: 723,
      saves: 289,
      thumbnail: "https://images.unsplash.com/photo-1537136727326-bc647b544d4c?w=800",
      description: "Street food paradise exploring Bangkok's best markets and local cuisines.",
    },
    {
      id: 8,
      userName: "Emily Rodriguez",
      userAvatar: "https://i.pravatar.cc/150?img=3",
      destination: "Lima, Peru",
      duration: "4 days",
      budget: "$2,200",
      likes: 456,
      saves: 178,
      thumbnail: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
      description: "Culinary capital experience with Peruvian cuisine and cooking classes.",
    },
    {
      id: 9,
      userName: "Marco Rossi",
      userAvatar: "https://i.pravatar.cc/150?img=14",
      destination: "Lyon, France",
      duration: "3 days",
      budget: "$2,600",
      likes: 534,
      saves: 201,
      thumbnail: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
      description: "France's gastronomic capital with Michelin stars and traditional bistros.",
    },
  ],
  'luxury-escapes': [
    {
      id: 10,
      userName: "James Wilson",
      userAvatar: "https://i.pravatar.cc/150?img=11",
      destination: "Dubai, UAE",
      duration: "5 days",
      budget: "$4,000",
      likes: 678,
      saves: 301,
      thumbnail: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
      description: "Ultra-modern Dubai experience with luxury hotels and world-class dining.",
    },
    {
      id: 11,
      userName: "Sophie Laurent",
      userAvatar: "https://i.pravatar.cc/150?img=6",
      destination: "Bora Bora, French Polynesia",
      duration: "7 days",
      budget: "$5,500",
      likes: 801,
      saves: 412,
      thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      description: "Ultimate luxury overwater bungalows with turquoise lagoons and tropical beauty.",
    },
    {
      id: 12,
      userName: "Alexander Mueller",
      userAvatar: "https://i.pravatar.cc/150?img=17",
      destination: "Maldives Luxury Resort",
      duration: "8 days",
      budget: "$6,000",
      likes: 945,
      saves: 567,
      thumbnail: "https://images.unsplash.com/photo-1516966556076-a6dd2a05c89d?w=800",
      description: "Five-star resort experience with private island access and water sports.",
    },
  ],
  'adventure-sports': [
    {
      id: 13,
      userName: "Chris Anderson",
      userAvatar: "https://i.pravatar.cc/150?img=7",
      destination: "Interlaken, Switzerland",
      duration: "6 days",
      budget: "$3,800",
      likes: 612,
      saves: 267,
      thumbnail: "https://images.unsplash.com/photo-1505228395891-9a51e7e86e81?w=800",
      description: "Adventure paradise with skydiving, bungee jumping, and mountain activities.",
    },
    {
      id: 14,
      userName: "Jordan Taylor",
      userAvatar: "https://i.pravatar.cc/150?img=4",
      destination: "Queenstown, New Zealand",
      duration: "7 days",
      budget: "$3,500",
      likes: 823,
      saves: 398,
      thumbnail: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
      description: "Adrenaline junkie's dream with rafting, skiing, and bungee jumping.",
    },
    {
      id: 15,
      userName: "Rachel Johnson",
      userAvatar: "https://i.pravatar.cc/150?img=18",
      destination: "Moab, Utah, USA",
      duration: "5 days",
      budget: "$2,500",
      likes: 567,
      saves: 234,
      thumbnail: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
      description: "Desert rock climbing and mountain biking in stunning red rock formations.",
    },
  ],
  'city-exploration': [
    {
      id: 16,
      userName: "David Martinez",
      userAvatar: "https://i.pravatar.cc/150?img=2",
      destination: "New York City, USA",
      duration: "4 days",
      budget: "$2,800",
      likes: 423,
      saves: 189,
      thumbnail: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
      description: "Fast-paced NYC adventure covering all the iconic spots and hidden gems!",
    },
    {
      id: 17,
      userName: "Isabella Rossi",
      userAvatar: "https://i.pravatar.cc/150?img=10",
      destination: "Barcelona, Spain",
      duration: "5 days",
      budget: "$2,400",
      likes: 534,
      saves: 267,
      thumbnail: "https://images.unsplash.com/photo-1562883676-8c6feb6f4785?w=800",
      description: "Gaudi's masterpieces, beaches, and vibrant street culture exploration.",
    },
    {
      id: 18,
      userName: "Thomas Mueller",
      userAvatar: "https://i.pravatar.cc/150?img=15",
      destination: "Singapore",
      duration: "4 days",
      budget: "$2,000",
      likes: 456,
      saves: 201,
      thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      description: "Modern Asia's gem with futuristic architecture and multicultural experiences.",
    },
  ],
};

interface CategoryDetail {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  itineraryCount: number;
}

export const categoryDetails: Record<string, CategoryDetail> = {
  'beach-paradise': {
    id: 'beach-paradise',
    name: 'Beach Paradise',
    description: 'Relax on pristine shores and tropical getaways',
    icon: '🏖️',
    color: 'from-cyan-500 to-blue-600',
    itineraryCount: 24,
  },
  'cultural-heritage': {
    id: 'cultural-heritage',
    name: 'Cultural Heritage',
    description: 'Explore historic sites and traditional experiences',
    icon: '🏛️',
    color: 'from-amber-500 to-orange-600',
    itineraryCount: 18,
  },
  'food-adventure': {
    id: 'food-adventure',
    name: 'Food Adventure',
    description: 'Culinary journeys and gastronomic delights',
    icon: '🍜',
    color: 'from-red-500 to-pink-600',
    itineraryCount: 32,
  },
  'luxury-escapes': {
    id: 'luxury-escapes',
    name: 'Luxury Escapes',
    description: 'Premium experiences and high-end destinations',
    icon: '💎',
    color: 'from-purple-500 to-indigo-600',
    itineraryCount: 15,
  },
  'adventure-sports': {
    id: 'adventure-sports',
    name: 'Adventure & Sports',
    description: 'Thrilling activities and outdoor exploration',
    icon: '⛰️',
    color: 'from-green-500 to-teal-600',
    itineraryCount: 21,
  },
  'city-exploration': {
    id: 'city-exploration',
    name: 'City Exploration',
    description: 'Urban adventures and metropolitan experiences',
    icon: '🏙️',
    color: 'from-slate-500 to-gray-600',
    itineraryCount: 28,
  },
};
