import React from 'react';
import ItineraryDetailClient from './ItineraryDetailClient';

// All itineraries data (combined from all categories)
const allItineraries: Record<string, any> = {
  '1': {
    id: 1,
    userName: "Emma Rodriguez",
    userAvatar: "https://i.pravatar.cc/150?img=5",
    destination: "Bali, Indonesia",
    duration: "10 days",
    budget: "$1,800",
    likes: 891,
    saves: 456,
    thumbnail: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    description: "Beach paradise with yoga retreats, temple visits, and stunning sunsets.",
    category: "Beach Paradise",
  },
  '2': {
    id: 2,
    userName: "Olivia Martinez",
    userAvatar: "https://i.pravatar.cc/150?img=9",
    destination: "Santorini, Greece",
    duration: "6 days",
    budget: "$3,500",
    likes: 1024,
    saves: 567,
    thumbnail: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
    description: "Luxury escape in the Greek islands with breathtaking views and amazing food.",
    category: "Beach Paradise",
  },
  '3': {
    id: 3,
    userName: "Carlos Santos",
    userAvatar: "https://i.pravatar.cc/150?img=13",
    destination: "Maldives",
    duration: "8 days",
    budget: "$5,000",
    likes: 1256,
    saves: 689,
    thumbnail: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    description: "Ultimate tropical paradise with overwater bungalows and crystal-clear waters.",
    category: "Beach Paradise",
  },
  '4': {
    id: 4,
    userName: "Sarah Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    destination: "Tokyo, Japan",
    duration: "7 days",
    budget: "$2,500",
    likes: 342,
    saves: 128,
    thumbnail: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    description: "Amazing week exploring Tokyo's vibrant neighborhoods and ancient temples.",
    category: "Cultural Heritage",
  },
  '5': {
    id: 5,
    userName: "Raj Patel",
    userAvatar: "https://i.pravatar.cc/150?img=14",
    destination: "Rome, Italy",
    duration: "6 days",
    budget: "$2,200",
    likes: 678,
    saves: 345,
    thumbnail: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    description: "Explore ancient ruins, Vatican City, and authentic Italian culture.",
    category: "Cultural Heritage",
  },
  '6': {
    id: 6,
    userName: "Michael Chen",
    userAvatar: "https://i.pravatar.cc/150?img=12",
    destination: "Paris, France",
    duration: "5 days",
    budget: "$3,200",
    likes: 567,
    saves: 234,
    thumbnail: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    description: "Romantic getaway through the City of Lights with amazing café stops.",
    category: "Food Adventure",
  },
  '7': {
    id: 7,
    userName: "Li Wei",
    userAvatar: "https://i.pravatar.cc/150?img=15",
    destination: "Bangkok, Thailand",
    duration: "8 days",
    budget: "$1,500",
    likes: 892,
    saves: 456,
    thumbnail: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800",
    description: "Street food paradise with authentic Thai cuisine and cooking classes.",
    category: "Food Adventure",
  },
  '8': {
    id: 8,
    userName: "James Wilson",
    userAvatar: "https://i.pravatar.cc/150?img=11",
    destination: "Dubai, UAE",
    duration: "5 days",
    budget: "$4,000",
    likes: 678,
    saves: 301,
    thumbnail: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    description: "Ultra-modern Dubai experience with luxury hotels and world-class dining.",
    category: "Luxury Escapes",
  },
  '9': {
    id: 9,
    userName: "Isabella Ferrari",
    userAvatar: "https://i.pravatar.cc/150?img=16",
    destination: "Monaco",
    duration: "4 days",
    budget: "$6,000",
    likes: 892,
    saves: 445,
    thumbnail: "https://images.unsplash.com/photo-1543716627-839b54f99c7b?w=800",
    description: "Opulent Mediterranean escape with yachts, casinos, and fine dining.",
    category: "Luxury Escapes",
  },
  '10': {
    id: 10,
    userName: "Alex Thompson",
    userAvatar: "https://i.pravatar.cc/150?img=17",
    destination: "Queenstown, New Zealand",
    duration: "9 days",
    budget: "$3,200",
    likes: 756,
    saves: 378,
    thumbnail: "https://images.unsplash.com/photo-1589802829199-c1c8c0e5d8c6?w=800",
    description: "Adrenaline-packed adventure with bungee jumping, skiing, and hiking.",
    category: "Adventure & Sports",
  },
  '11': {
    id: 11,
    userName: "Maria Silva",
    userAvatar: "https://i.pravatar.cc/150?img=18",
    destination: "Costa Rica",
    duration: "12 days",
    budget: "$2,800",
    likes: 923,
    saves: 512,
    thumbnail: "https://images.unsplash.com/photo-1606353836139-72dc0f35b33d?w=800",
    description: "Zip-lining through rainforests, surfing, and volcano exploration.",
    category: "Adventure & Sports",
  },
  '12': {
    id: 12,
    userName: "David Kim",
    userAvatar: "https://i.pravatar.cc/150?img=8",
    destination: "New York City, USA",
    duration: "4 days",
    budget: "$2,800",
    likes: 423,
    saves: 189,
    thumbnail: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
    description: "Fast-paced NYC adventure covering all the iconic spots and hidden gems!",
    category: "City Exploration",
  },
  '13': {
    id: 13,
    userName: "Sophie Laurent",
    userAvatar: "https://i.pravatar.cc/150?img=19",
    destination: "London, England",
    duration: "6 days",
    budget: "$2,500",
    likes: 634,
    saves: 298,
    thumbnail: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    description: "Royal palaces, world-class museums, and vibrant neighborhoods.",
    category: "City Exploration",
  },
};

export { allItineraries };

// Required for static export
export function generateStaticParams() {
  return Object.keys(allItineraries).map(id => ({ id }));
}

export default async function ItineraryDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <ItineraryDetailClient itineraryId={id} />;
}
