name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy Stage
  jobs:
  - job: BuildAndDeployJob
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Azure-Static-Web-Apps-purple-sand-06148da0f-variable-group

    steps:
    - checkout: self
      submodules: true

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Use Node.js 18.x'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build Next.js app'

    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SAND_06148DA0F)
        app_location: "/"
        api_location: ""     # set this if you have an /api folder
        output_location: ""  # leave empty for Next.js SSR
