import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@kiwicom/orbit-components/lib/tailwind.css"; // Must be FIRST
import "./globals.css";
import Auth0ProviderWrapper from "../components/Auth0ProviderWrapper";
import OrbitWrapper from "./OrbitWrapper";
import { ThemeProvider } from "../components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Auth0ProviderWrapper>
          <ThemeProvider>
            <OrbitWrapper>
              {children}
            </OrbitWrapper>
          </ThemeProvider>
        </Auth0ProviderWrapper>
      </body>
    </html>
  );
}